name: mi_tienda_app
description: "Venta Rápida Minimarket - Sistema POS Offline-First"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  
  # State Management
  provider: ^6.1.2
  
  # Scanner
  mobile_scanner: ^7.1.2
  
  # UI
  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  
  # Audio feedback
  audioplayers: ^6.5.1
  
  # Utilities
  uuid: ^4.5.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
    - assets/images/
